name: CI

# Trigger the workflow...
on:
  push:
  pull_request:

jobs:

  Test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install System Dependencies
      run: sudo apt-get install -y libxslt-dev

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        # NOTE: we can ignore nokogiri install speed considerations in view of caching

    - name: Restore HTMLProofer cache
      id: cache-htmlproofer
      uses: actions/cache/restore@v4
      with:
        path: .htmlproofer-cache
        key: ${{ runner.os }}-html-proofer-
    - run: |
        git add .htmlproofer-cache
        git status
    - name: Test with HTMLProofer
      # see proof.rb for the fine-tuning of html-proofer
      run: |
        bundle exec htmlproofer _site --cache '{ "timeframe": { "external": "1d", "internal": "1d" }, "storage_dir": ".htmlproofer-cache" }' --log-level debug
    - run: |
        git status
        git diff
      if: always()
    - name: Save HTMLProofer cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: .htmlproofer-cache
        key: ${{ runner.os }}-html-proofer-${{ hashFiles('.htmlproofer-cache') }}